// Sports Market Data extracted from PDF
// This file contains all betting markets organized by sport

const sportsData = {
    football: {
        name: "Football",
        icon: "🏈",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Player Props", subcategories: ["Touchdowns", "Passing Touchdowns", "Passing Yards", "Receiving Yards", "Rushing yards", "Carries", "Pass Completions", "Receptions"] },
            { name: "Quarters", subcategories: [] },
            { name: "Halves", subcategories: [] },
            { name: "Totals", subcategories: [] },
            { name: "More", subcategories: [] },
            { name: "All", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Game Lines", subcategories: [] },
            { name: "Halves", subcategories: [] },
            { name: "Quarters", subcategories: [] },
            { name: "Game Props", subcategories: [] },
            { name: "Player Props", subcategories: ["Passing Props", "Rushing Props", "Receiving Props", "TD Props"] },
            { name: "Special Teams", subcategories: [] },
            { name: "Totals", subcategories: [] }
        ],
        markets: [
            { id: "fb_1", specificMarket: "Winner (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_2", specificMarket: "1x2", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_3", specificMarket: "Handicap (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_4", specificMarket: "Total (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_5", specificMarket: "1st Half - Total", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_6", specificMarket: "1st Half - Handicap", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_7", specificMarket: "1st Half - Draw No Bet", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_8", specificMarket: "Halftime/Fulltime", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_9", specificMarket: "Draw No Bet (incl. Overtime)", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_10", specificMarket: "1x2 (incl. Overtime)", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "fb_11", specificMarket: "Home Odd/Even", sportsradarType: "Main", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_12", specificMarket: "Away Odd/Even", sportsradarType: "Main", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_13", specificMarket: "Home Odd/Even (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_14", specificMarket: "Away Odd/Even (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_15", specificMarket: "1st Half - 1x2", sportsradarType: "Halftime", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_16", specificMarket: "1st Half - Odd/Even", sportsradarType: "Halftime", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_17", specificMarket: "1st Half - Home Odd/Even", sportsradarType: "Halftime", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_18", specificMarket: "1st Half - Away Odd/Even", sportsradarType: "Halftime", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_19", specificMarket: "2nd Half - 1x2", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_20", specificMarket: "2nd Half - Handicap (incl. Overtime)", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_21", specificMarket: "2nd Half - Total (incl. Overtime)", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_22", specificMarket: "2nd Half - Draw No Bet (incl. Overtime)", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_23", specificMarket: "2nd Half - 1x2 (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_24", specificMarket: "2nd Half - Handicap", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_25", specificMarket: "2nd Half - Total", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_26", specificMarket: "Winning Margin", sportsradarType: "Points", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_27", specificMarket: "Highest Scoring Quarter", sportsradarType: "Points", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_28", specificMarket: "Home Total (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_29", specificMarket: "Away Total (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_30", specificMarket: "Highest Scoring Half", sportsradarType: "Points", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "fb_31", specificMarket: "Race to X (incl. Overtime)", sportsradarType: "Points", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_32", specificMarket: "Will There Be Overtime", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_33", specificMarket: "Odd/Even", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_34", specificMarket: "Odd/Even (incl. Overtime)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_35", specificMarket: "Total Touchdowns (incl. Overtime)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_36", specificMarket: "Total Field Goals Made (incl. Overtime)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_37", specificMarket: "Total Turnovers (incl. Overtime)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_38", specificMarket: "Total Sacks (incl. Overtime)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_39", specificMarket: "1st Field Goal Made (incl Overtime)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_40", specificMarket: "1st Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_41", specificMarket: "2nd Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_42", specificMarket: "3rd Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_43", specificMarket: "4th Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_44", specificMarket: "1st Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_45", specificMarket: "2nd Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_46", specificMarket: "3rd Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_47", specificMarket: "4th Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_48", specificMarket: "1st Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_49", specificMarket: "2nd Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_50", specificMarket: "3rd Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_51", specificMarket: "4th Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_52", specificMarket: "1st Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_53", specificMarket: "2nd Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_54", specificMarket: "3rd Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_55", specificMarket: "4th Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_56", specificMarket: "Player Passing Yards (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_57", specificMarket: "Player Pass Completions (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_58", specificMarket: "Player Passing TDs (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_59", specificMarket: "Player Carries (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rushing Props" },
            { id: "fb_60", specificMarket: "Player Rushing Yards (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rushing Props" },
            { id: "fb_61", specificMarket: "Player Receiving (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Receiving Props" },
            { id: "fb_62", specificMarket: "Player Receptions (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Receiving Props" },
            { id: "fb_63", specificMarket: "X Total Passing Yards (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_64", specificMarket: "X Total Pass Completions (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_65", specificMarket: "X Total Passing TDs (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Passing Props" },
            { id: "fb_66", specificMarket: "X Total Carries (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rushing Props" },
            { id: "fb_67", specificMarket: "X Total Rushing Yards (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rushing Props" },
            { id: "fb_68", specificMarket: "X Total Receiving yards (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Receiving Props" },
            { id: "fb_69", specificMarket: "X Total Receptions (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Receiving Props" },
            { id: "fb_70", specificMarket: "Player to Score 1st Touchdown (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "TD Props" },
            { id: "fb_71", specificMarket: "Player Touchdowns (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "TD Props" },
            { id: "fb_72", specificMarket: "Winner (incl. OT) & Total (incl. OT)", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_73", specificMarket: "1st Drive - Result", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_74", specificMarket: "Handicap (incl. OT) & Total (incl. OT)", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_75", specificMarket: "4th Quarter - 1x2 (incl. Overtime)", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_76", specificMarket: "4th Quarter - Draw No Bet (incl. Overtime)", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_77", specificMarket: "4th Quarter - Handicap (incl. Overtime)", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_78", specificMarket: "4th Quarter - Total (incl. Overtime)", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "fb_79", specificMarket: "1st Quarter 1x2 & 1st Quarter Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_80", specificMarket: "1st Quarter Handicap & 1st Quarter Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_81", specificMarket: "1st Half 1x2 & 1st Half Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "fb_82", specificMarket: "1st Half Handicap & 1st Half Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" }
        ]
    },
    basketball: {
        name: "Basketball",
        icon: "🏀",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Player Props", subcategories: ["Points", "3pt", "Assists", "Rebounds", "Blocks", "Steals", "Combos"] },
            { name: "Quarters", subcategories: [] },
            { name: "Halves", subcategories: [] },
            { name: "Totals", subcategories: [] },
            { name: "More", subcategories: [] },
            { name: "All", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Game Lines", subcategories: [] },
            { name: "Halves", subcategories: [] },
            { name: "Quarters", subcategories: [] },
            { name: "Points", subcategories: [] },
            { name: "Game Props", subcategories: [] },
            { name: "Player Props", subcategories: ["Points", "Rebounds", "Assists", "3-Pointers", "Blocks", "Steals", "Combos"] }
        ],
        markets: [
            { id: "bb_1", specificMarket: "Winner (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_2", specificMarket: "Total (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_3", specificMarket: "Handicap (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_4", specificMarket: "1st Half - Total", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_5", specificMarket: "1st Half - Handicap", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_6", specificMarket: "1st Half - Draw No Bet", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_7", specificMarket: "Halftime/Fulltime", sportsradarType: "Main", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_8", specificMarket: "Handicap", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_9", specificMarket: "Total", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_10", specificMarket: "1x2", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_11", specificMarket: "1st Half - 1x2", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_12", specificMarket: "1st Half - Odd/Even", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_13", specificMarket: "1st Half - Home Total", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_14", specificMarket: "1st Half - Away Total", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_15", specificMarket: "2nd Half - 1x2", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_16", specificMarket: "2nd Half - Handicap", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_17", specificMarket: "2nd Half - Total", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_18", specificMarket: "2nd Half - Odd/Even", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_19", specificMarket: "2nd Half - Draw No Bet", sportsradarType: "2nd Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_20", specificMarket: "1st Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_21", specificMarket: "1st Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_22", specificMarket: "1st Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_23", specificMarket: "1st Quarter - Odd/Even", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_24", specificMarket: "1st Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_25", specificMarket: "2nd Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_26", specificMarket: "2nd Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_27", specificMarket: "2nd Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_28", specificMarket: "2nd Quarter - Odd/Even", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_29", specificMarket: "2nd Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_30", specificMarket: "3rd Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_31", specificMarket: "3rd Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_32", specificMarket: "3rd Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_33", specificMarket: "3rd Quarter - Odd/Even", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_34", specificMarket: "3rd Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_35", specificMarket: "4th Quarter - 1x2", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_36", specificMarket: "4th Quarter - Handicap", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_37", specificMarket: "4th Quarter - Total", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_38", specificMarket: "4th Quarter - Odd/Even", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_39", specificMarket: "4th Quarter - Draw No Bet", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_40", specificMarket: "Highest Scoring Quarter", sportsradarType: "Quarters", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_41", specificMarket: "Will There Be Overtime", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_42", specificMarket: "Race To X Points (incl. Overtime)", sportsradarType: "Specials", active: false, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_43", specificMarket: "Home Total (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_44", specificMarket: "Away Total (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_45", specificMarket: "Odd/Even (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_46", specificMarket: "Winning Margin (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_47", specificMarket: "Winner & Total (incl. Overtime)", sportsradarType: "Points", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_48", specificMarket: "Race To X Points", sportsradarType: "Points", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_49", specificMarket: "Draw No Bet", sportsradarType: "Others", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bb_50", specificMarket: "Player Points (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Points" },
            { id: "bb_51", specificMarket: "Player Assists (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Assists" },
            { id: "bb_52", specificMarket: "Player Blocks (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Blocks" },
            { id: "bb_53", specificMarket: "Player Rebounds (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rebounds" },
            { id: "bb_54", specificMarket: "Player Steals (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Steals" },
            { id: "bb_55", specificMarket: "Player 3-point Field Goals (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "3-Pointers" },
            { id: "bb_56", specificMarket: "X Total Points (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Points" },
            { id: "bb_57", specificMarket: "X Total Assists (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Assists" },
            { id: "bb_58", specificMarket: "X Total Rebounds (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Rebounds" },
            { id: "bb_59", specificMarket: "X Total 3-point Field Goals (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "3-Pointers" },
            { id: "bb_60", specificMarket: "First Point Scorer (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Points" },
            { id: "bb_61", specificMarket: "Double Double (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Combos" },
            { id: "bb_62", specificMarket: "Triple Double (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Combos" },
            { id: "bb_63", specificMarket: "1st Quarter - Home Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_64", specificMarket: "1st Quarter - Away Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_65", specificMarket: "2nd Quarter - Home Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_66", specificMarket: "2nd Quarter - Away Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_67", specificMarket: "3rd Quarter - Home Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_68", specificMarket: "3rd Quarter - Away Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_69", specificMarket: "4th Quarter - Home Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_70", specificMarket: "4th Quarter - Away Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_71", specificMarket: "Home To Win All Quarters", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_72", specificMarket: "Away To Win All Quarters", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_73", specificMarket: "Any Team To Win All Quarters", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_74", specificMarket: "Team To Win All Quarters", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_75", specificMarket: "Highest Scoring Quarter - Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_76", specificMarket: "Lowest Scoring Quarter - Total", sportsradarType: "Quarters", active: false, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_77", specificMarket: "Home Total Max Consecutive Points", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_78", specificMarket: "Away Total Max Consecutive Points", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_79", specificMarket: "Any Team Total Max Consecutive Points", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_80", specificMarket: "Highest Scoring Half", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_81", specificMarket: "Home to Lead By", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_82", specificMarket: "Away To Lead By", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_83", specificMarket: "Any Team To Lead By", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_84", specificMarket: "1st Point (incl. Overtime)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_85", specificMarket: "1st Quarter - Last Point", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_86", specificMarket: "2nd Quarter - Last Point", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_87", specificMarket: "1st Free Throw Scored", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_88", specificMarket: "1st Timeout", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_89", specificMarket: "Home To Win Both Halves", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_90", specificMarket: "Away To Win Both Halves", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_91", specificMarket: "Any Team To Win Both Halves", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_92", specificMarket: "Team To Win Both Halves", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_93", specificMarket: "Point Range (high)", sportsradarType: "Points", active: false, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_94", specificMarket: "Point Range (low)", sportsradarType: "Points", active: false, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_95", specificMarket: "Total (over-exact-under)", sportsradarType: "Points", active: false, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_96", specificMarket: "Winning Margin (incl. Overtime)", sportsradarType: "Others", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_97", specificMarket: "2nd Half - Handicap (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_98", specificMarket: "2nd Half - Total (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_99", specificMarket: "2nd Half - 1x2 (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_100", specificMarket: "2nd Half - Draw No Bet (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_101", specificMarket: "2nd Half - Odd/Even (incl. Overtime)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "bb_102", specificMarket: "1st Quarter - Winning Margin", sportsradarType: "Misc", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_103", specificMarket: "2nd Quarter - Winning Margin", sportsradarType: "Misc", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_104", specificMarket: "3rd Quarter - Winning Margin", sportsradarType: "Misc", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_105", specificMarket: "4th Quarter - Winning Margin", sportsradarType: "Misc", active: true, suggestedCategory: "Quarters", suggestedSubcategory: "" },
            { id: "bb_106", specificMarket: "Any Team Winning Margin (incl. Overtime)", sportsradarType: "Misc", active: true, suggestedCategory: "Points", suggestedSubcategory: "" },
            { id: "bb_107", specificMarket: "1x2 & Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_108", specificMarket: "Handicap (including OT) & Total (including OT)", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_109", specificMarket: "1st Quarter 1x2 & 1st Quarter Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_110", specificMarket: "1st Quarter Handicap & 1st Quarter Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_111", specificMarket: "1st Half 1x2 & 1st Half Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bb_112", specificMarket: "1st Half Handicap & 1st Half Total", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" }
        ]
    },
    soccer: {
        name: "Soccer",
        icon: "⚽",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Player Props", subcategories: ["Goals", "Assists", "Cards", "Shots", "Passes", "Tackles"] },
            { name: "Halves", subcategories: [] },
            { name: "Totals", subcategories: [] },
            { name: "More", subcategories: [] },
            { name: "All", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Match Lines", subcategories: [] },
            { name: "Goals", subcategories: [] },
            { name: "Halves", subcategories: [] },
            { name: "Corners", subcategories: [] },
            { name: "Goalscorers", subcategories: [] },
            { name: "Game Props", subcategories: [] },
            { name: "Player Props", subcategories: ["Goals", "Assists", "Shots", "Cards"] },
            { name: "Others", subcategories: [] }
        ],
        markets: [
            { id: "sc_1", specificMarket: "1x2", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_2", specificMarket: "Total", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_3", specificMarket: "Handicap", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_4", specificMarket: "Double Chance", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_5", specificMarket: "Draw No Bet", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_6", specificMarket: "Halftime/Fulltime", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_7", specificMarket: "Handicap (1x2)", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_8", specificMarket: "Both Teams To Score", sportsradarType: "Main Markets", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_9", specificMarket: "Correct Score", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_10", specificMarket: "1st Goal", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_11", specificMarket: "Both Teams To Score", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_12", specificMarket: "Odd/Even", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_13", specificMarket: "Home Total", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_14", specificMarket: "Away Total", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_15", specificMarket: "Which Team To Score", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_16", specificMarket: "Home Exact Goals", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_17", specificMarket: "Away Clean Sheet", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_18", specificMarket: "Home To Score In Both Halves", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_19", specificMarket: "Away To Score In Both Halves", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_20", specificMarket: "Both Halves Over 1.5", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_21", specificMarket: "Both Halves Under 1.5", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_22", specificMarket: "1st Half - 1x2", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_23", specificMarket: "1st Half - Total", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_24", specificMarket: "1st Half - Handicap", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_25", specificMarket: "1st Half - Double Chance", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_26", specificMarket: "1st Half - Draw No Bet", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_27", specificMarket: "1st Half - Correct Score", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_28", specificMarket: "1st Half - Both Teams To Score", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_29", specificMarket: "1st Half - Home Total", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_30", specificMarket: "1st Half - Away Total", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_31", specificMarket: "1st Half - 1st Goal", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_32", specificMarket: "1st Half - Home Clean Sheet", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_33", specificMarket: "Total Corners", sportsradarType: "Corners", active: false, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_34", specificMarket: "1st Corner", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_35", specificMarket: "1st Half - Total Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_36", specificMarket: "Corner Handicap", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_37", specificMarket: "1st Half - Corner Handicap", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_38", specificMarket: "Last Corner", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_39", specificMarket: "Home Total Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_40", specificMarket: "Away Total Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_41", specificMarket: "1st Goalscorer (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_42", specificMarket: "Anytime Goalscorer (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_43", specificMarket: "Last Goalscorer (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_44", specificMarket: "Player to score (incl. overtime) (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_45", specificMarket: "Home To Win Both Halves", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_46", specificMarket: "To Qualify", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_47", specificMarket: "Will There Be Overtime", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_48", specificMarket: "Will There Be A Penalty Shootout", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_49", specificMarket: "Player Goals (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Goals" },
            { id: "sc_50", specificMarket: "Player Assists (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Assists" },
            { id: "sc_51", specificMarket: "Player Shots (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "sc_52", specificMarket: "Player To Be Carded (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Cards" },
            { id: "sc_53", specificMarket: "Correct Score [0:0]", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "sc_54", specificMarket: "Away Exact Goals", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_55", specificMarket: "Goal Range (6+)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_56", specificMarket: "Goal Range (7+)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_57", specificMarket: "Highest Scoring Half", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_58", specificMarket: "Home Clean Sheet", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_59", specificMarket: "Home Highest Scoring Half", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_60", specificMarket: "Away Highest Scoring Half", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_61", specificMarket: "Home Odd/Even", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_62", specificMarket: "Away Odd/Even", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "sc_63", specificMarket: "1st Half - Exact Goals (2+)", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_64", specificMarket: "1st Half - Exact Goals (3+)", sportsradarType: "1st Half", active: true, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_65", specificMarket: "1st Half - Away Clean Sheet", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_66", specificMarket: "1st Half - Odd/Even", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_67", specificMarket: "1st Half - Handicap (1x2)", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_68", specificMarket: "1st Half - Sending Off", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_69", specificMarket: "1st Half - Home Sending Off", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_70", specificMarket: "1st Half - Away Sending Off", sportsradarType: "1st Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_71", specificMarket: "2nd Half - 1x2", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_72", specificMarket: "2nd Half - Total", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_73", specificMarket: "2nd Half - Handicap", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_74", specificMarket: "2nd Half - Exact Goals", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_75", specificMarket: "2nd Half - Double Chance", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_76", specificMarket: "2nd Half - Draw No Bet", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_77", specificMarket: "2nd Half - Correct Score", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_78", specificMarket: "2nd Half - Both Teams To Score", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_79", specificMarket: "2nd Half - Home Total", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_80", specificMarket: "2nd Half - Away Total", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_81", specificMarket: "2nd Half - 1st Goal", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_82", specificMarket: "2nd Half - Home Clean Sheet", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_83", specificMarket: "2nd Half - Away Clean Sheet", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_84", specificMarket: "2nd Half - Odd/Even", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_85", specificMarket: "2nd Half - Handicap (1x2)", sportsradarType: "2nd Half", active: false, suggestedCategory: "Halves", suggestedSubcategory: "" },
            { id: "sc_86", specificMarket: "1st Half - 1st Corner", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_87", specificMarket: "Corner 1x2", sportsradarType: "Corners", active: false, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_88", specificMarket: "1st Half - Corner 1x2", sportsradarType: "Corners", active: false, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_89", specificMarket: "Odd/Even Corners", sportsradarType: "Corners", active: false, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_90", specificMarket: "1st Half - Odd/Even Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_91", specificMarket: "1st Half - Last Corner", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_92", specificMarket: "Home Corner Range", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_93", specificMarket: "1st Half - Home Exact Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_94", specificMarket: "Away Corner Range", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_95", specificMarket: "1st Half - Away Exact Corners", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_96", specificMarket: "Corner Range", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_97", specificMarket: "1st Half - Corner Range", sportsradarType: "Corners", active: true, suggestedCategory: "Corners", suggestedSubcategory: "" },
            { id: "sc_98", specificMarket: "Anytime Goalscorer & Correct Score (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_99", specificMarket: "1st Goalscorer & Correct Score (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_100", specificMarket: "Anytime Goalscorer & 1x2 (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_101", specificMarket: "1st Goalscorer & 1x2 (Factor)", sportsradarType: "Scorers", active: true, suggestedCategory: "Goalscorers", suggestedSubcategory: "" },
            { id: "sc_102", specificMarket: "Halftime/Fulltime Correct Score", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_103", specificMarket: "Away To Win Both Halves", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_104", specificMarket: "Home To Win Either Half", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_105", specificMarket: "Away To Win Either Half", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_106", specificMarket: "Home Win To Nil", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_107", specificMarket: "Away Win To Nil", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_108", specificMarket: "When Will The 1st Goal Be Scored (10 Min Interval)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_109", specificMarket: "When Will The 1st Goal Be Scored (15 Min Interval)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_110", specificMarket: "Winning Margin", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_111", specificMarket: "Home No Bet", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_112", specificMarket: "Away No Bet", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_113", specificMarket: "Winning Method", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_114", specificMarket: "1st Goal & 1x2", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_115", specificMarket: "10 Minutes - 1x2 From 1 To 10", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_116", specificMarket: "Last Goal", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_117", specificMarket: "Which Team Will Win The Final", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_118", specificMarket: "Which Team Will Win The 3rd Place Final", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_119", specificMarket: "Overtime & Goal", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_120", specificMarket: "1x2 & Total", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_121", specificMarket: "1x2 & Both Teams To Score", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_122", specificMarket: "Total & Both Teams To Score", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_123", specificMarket: "1st Half - 1x2 & Total", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_124", specificMarket: "1st Half - 1x2 & Both Teams To Score", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_125", specificMarket: "Home To Win", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_126", specificMarket: "Away To Win", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_127", specificMarket: "Any Team To Win", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_128", specificMarket: "Double Chance & Both Teams To Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_129", specificMarket: "1st Half - Double Chance & Both Teams To Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_130", specificMarket: "2nd Half - Double Chance & Both Teams To Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_131", specificMarket: "Multiscores", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_132", specificMarket: "Multigoals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_133", specificMarket: "1st Half - Multigoals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_134", specificMarket: "2nd Half - Multigoals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_135", specificMarket: "Home Multigoals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_136", specificMarket: "Away Multigoals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_137", specificMarket: "Double Chance (match) & 1st Half Both Teams Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_138", specificMarket: "Double Chance (match) & 2nd Half Both Teams Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_139", specificMarket: "Exact Goals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_140", specificMarket: "1st/2nd Half Both Teams To Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_141", specificMarket: "2nd Half - 1x2 & Total", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_142", specificMarket: "2nd Half - 1x2 & Both Teams To Score", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_143", specificMarket: "Double Chance & Total", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_144", specificMarket: "Halftime/Fulltime & Total", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_145", specificMarket: "Halftime/Fulltime & 1st Half Total", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_146", specificMarket: "Halftime/Fulltime & Exact Goals", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_147", specificMarket: "1st Half Result Or Match Result", sportsradarType: "Others", active: false, suggestedCategory: "Others", suggestedSubcategory: "" },
            { id: "sc_148", specificMarket: "X Total Shots (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "sc_149", specificMarket: "X Total Shots On Goal (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "sc_150", specificMarket: "X Total Passes (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "" },
            { id: "sc_151", specificMarket: "X Total Tackles (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "" },
            { id: "sc_152", specificMarket: "Player Shots On Goal (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "sc_153", specificMarket: "Player Passes (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "" },
            { id: "sc_154", specificMarket: "Player Tackles (incl. Overtime)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "" },
            { id: "sc_155", specificMarket: "Home Or Over", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_156", specificMarket: "Draw Or Over", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_157", specificMarket: "Away Or Over", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_158", specificMarket: "Home Or Under", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_159", specificMarket: "Draw Or Under", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_160", specificMarket: "Away Or Under", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_161", specificMarket: "Home Or Both Teams To Score", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_162", specificMarket: "Draw Or Both Teams To Score", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_163", specificMarket: "Away Or Both Teams To Score", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_164", specificMarket: "Home Or Any Clean Sheet", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_165", specificMarket: "Draw Or Any Clean Sheet", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "sc_166", specificMarket: "Away Or Any Clean Sheet", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" }
        ]
    },
    hockey: {
        name: "Ice Hockey",
        icon: "🏒",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Player Props", subcategories: ["Points", "Goals", "Assists", "Shots", "Saves"] },
            { name: "Period", subcategories: [] },
            { name: "Totals", subcategories: [] },
            { name: "More", subcategories: [] },
            { name: "All", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Game Lines", subcategories: [] },
            { name: "Goals", subcategories: [] },
            { name: "Periods", subcategories: [] },
            { name: "Game Props", subcategories: [] },
            { name: "Player Props", subcategories: ["Goals", "Assists", "Points", "Shots", "Saves"] }
        ],
        markets: [
            { id: "hk_1", specificMarket: "1x2", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_2", specificMarket: "Winner (incl. Overtime And Penalties)", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_3", specificMarket: "Total (incl. Overtime And Penalties)", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_4", specificMarket: "Handicap", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_5", specificMarket: "Double Chance", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_6", specificMarket: "Handicap (1x2)", sportsradarType: "Main Markets", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_7", specificMarket: "1st Goal", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_8", specificMarket: "1x2 & Total", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_9", specificMarket: "Winning Margin", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_10", specificMarket: "Last Goal", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_11", specificMarket: "Home Total", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_12", specificMarket: "Away Total", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_13", specificMarket: "1st Period - 1x2", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_14", specificMarket: "1st Period - Double Chance", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_15", specificMarket: "1st Period - Draw No Bet", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_16", specificMarket: "1st Period - Handicap", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_17", specificMarket: "1st Period - Total", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_18", specificMarket: "2nd Period - 1x2", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_19", specificMarket: "2nd Period - Total", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_20", specificMarket: "3rd Period - 1x2", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_21", specificMarket: "3rd Period - Total", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_22", specificMarket: "Highest Scoring Period", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_23", specificMarket: "Draw No Bet", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "hk_24", specificMarket: "Will There Be Overtime", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "hk_25", specificMarket: "Player Goals (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Goals" },
            { id: "hk_26", specificMarket: "Player Assists (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Assists" },
            { id: "hk_27", specificMarket: "Player Points (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Points" },
            { id: "hk_28", specificMarket: "Player Shots On Goal (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "hk_29", specificMarket: "Player Saves (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Saves" },
            { id: "hk_30", specificMarket: "X Total Points (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Points" },
            { id: "hk_31", specificMarket: "X Total Shots On Goal (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Shots" },
            { id: "hk_32", specificMarket: "X Total Saves (incl. Overtime)", sportsradarType: "Player Props", active: true, suggestedCategory: "Player Props", suggestedSubcategory: "Saves" },
            { id: "hk_33", specificMarket: "Total", sportsradarType: "Main Markets", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_34", specificMarket: "Handicap (incl. Overtime And Penalties)", sportsradarType: "Main Markets", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "hk_35", specificMarket: "Correct Score", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_36", specificMarket: "Both Teams To Score", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_37", specificMarket: "Odd/Even", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_38", specificMarket: "Odd/Even (incl. Overtime And Penalties)", sportsradarType: "Goals", active: true, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_39", specificMarket: "Home Total (incl. Overtime And Penalties)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_40", specificMarket: "Away Total (incl. Overtime And Penalties)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_41", specificMarket: "Home Clean Sheet (incl. Overtime And Penalties)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_42", specificMarket: "Away Clean Sheet (incl. Overtime And Penalties)", sportsradarType: "Goals", active: false, suggestedCategory: "Goals", suggestedSubcategory: "" },
            { id: "hk_43", specificMarket: "1st Period - 1st Goal", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_44", specificMarket: "1st Period - Last Team To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_45", specificMarket: "1st Period - Both Teams To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_46", specificMarket: "1st Period - Odd/Even", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_47", specificMarket: "2nd Period - Double Chance", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_48", specificMarket: "2nd Period - Draw No Bet", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_49", specificMarket: "2nd Period - Handicap", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_50", specificMarket: "2nd Period - 1st Goal", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_51", specificMarket: "2nd Period - Last Team To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_52", specificMarket: "2nd Period - Both Teams To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_53", specificMarket: "2nd Period - Odd/Even", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_54", specificMarket: "3rd Period - Double Chance", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_55", specificMarket: "3rd Period - Draw No Bet", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_56", specificMarket: "3rd Period - Handicap", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_57", specificMarket: "3rd Period - 1st Goal", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_58", specificMarket: "3rd Period - Last Team To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_59", specificMarket: "3rd Period - Both Teams To Score", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_60", specificMarket: "3rd Period - Odd/Even", sportsradarType: "Periods", active: true, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_61", specificMarket: "1st Period - Home Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_62", specificMarket: "1st Period - Away Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_63", specificMarket: "2nd Period - Home Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_64", specificMarket: "2nd Period - Away Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_65", specificMarket: "3rd Period - Home Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" },
            { id: "hk_66", specificMarket: "3rd Period - Away Total", sportsradarType: "Periods", active: false, suggestedCategory: "Periods", suggestedSubcategory: "" }
        ]
    },
    tennis: {
        name: "Tennis",
        icon: "🎾",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Player Props", subcategories: ["Sets", "Games"] },
            { name: "Sets", subcategories: [] },
            { name: "Games", subcategories: [] },
            { name: "More", subcategories: [] },
            { name: "All", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Match Lines", subcategories: [] },
            { name: "Sets", subcategories: [] },
            { name: "Games", subcategories: [] },
            { name: "Game Props", subcategories: [] }
        ],
        markets: [
            { id: "tn_1", specificMarket: "Winner", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "tn_2", specificMarket: "Total Games", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "tn_3", specificMarket: "Game Handicap", sportsradarType: "Main Markets", active: true, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "tn_4", specificMarket: "1st Set - Winner", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_5", specificMarket: "Set Handicap", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_6", specificMarket: "1st Set - Correct Score", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_7", specificMarket: "1st Set - Game Handicap", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_8", specificMarket: "2nd Set - Winner", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_9", specificMarket: "Exact Sets Best of 3", sportsradarType: "Sets", active: true, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_10", specificMarket: "Exact Sets Best of 5", sportsradarType: "Sets", active: true, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_11", specificMarket: "Home To Win A Set", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_12", specificMarket: "Away To Win A Set", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_13", specificMarket: "1st Set - Will There Be A Tiebreak", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_14", specificMarket: "Home Total Games", sportsradarType: "Games", active: true, suggestedCategory: "Games", suggestedSubcategory: "" },
            { id: "tn_15", specificMarket: "Away Total Games", sportsradarType: "Games", active: false, suggestedCategory: "Games", suggestedSubcategory: "" },
            { id: "tn_16", specificMarket: "Odd/Even Games", sportsradarType: "Games", active: false, suggestedCategory: "Games", suggestedSubcategory: "" },
            { id: "tn_17", specificMarket: "Will There Be A Tiebreak", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_18", specificMarket: "Double Result (1st Set/Match)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_19", specificMarket: "Winner & Total", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_20", specificMarket: "1st Set - Total Games", sportsradarType: "Main Markets", active: false, suggestedCategory: "Match Lines", suggestedSubcategory: "" },
            { id: "tn_21", specificMarket: "Any Set To Nil", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_22", specificMarket: "Total Sets", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_23", specificMarket: "1st Set - Exact Score Group", sportsradarType: "Sets", active: false, suggestedCategory: "Sets", suggestedSubcategory: "" },
            { id: "tn_24", specificMarket: "Correct Score Best of 3 (In Sets)", sportsradarType: "Games", active: false, suggestedCategory: "Games", suggestedSubcategory: "" },
            { id: "tn_25", specificMarket: "Correct Score Best of 5 (In Sets)", sportsradarType: "Games", active: false, suggestedCategory: "Games", suggestedSubcategory: "" },
            { id: "tn_26", specificMarket: "1st Set - Winner & Total", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_27", specificMarket: "Home To Win Exactly 1 Set", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_28", specificMarket: "Away To Win Exactly 1 Set", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_29", specificMarket: "Home To Win Exactly 2 Sets", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_30", specificMarket: "Away To Win Exactly 2 Sets", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_31", specificMarket: "Match To End 0:2", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_32", specificMarket: "Match To End 2:0", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_33", specificMarket: "Match To End 0:3", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "tn_34", specificMarket: "Match To End 3:0", sportsradarType: "Misc", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" }
        ]
    },
    baseball: {
        name: "Baseball",
        icon: "⚾",
        currentCategories: [
            { name: "Main", subcategories: [] },
            { name: "Runs", subcategories: [] },
            { name: "Specials", subcategories: [] },
            { name: "Player Props", subcategories: [] }
        ],
        suggestedCategories: [
            { name: "Popular", subcategories: [] },
            { name: "Game Lines", subcategories: [] },
            { name: "Runs", subcategories: [] },
            { name: "Game Props", subcategories: [] },
            { name: "Player Props", subcategories: ["Batter Props", "Pitcher Props"] }
        ],
        markets: [
            { id: "bs_1", specificMarket: "Winner (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_2", specificMarket: "Total (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_3", specificMarket: "Handicap (incl. Overtime)", sportsradarType: "Main", active: true, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_4", specificMarket: "1st Inning - 1x2", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_5", specificMarket: "Innings 1 To 5 - Handicap", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_6", specificMarket: "Innings 1 To 5 - Total", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_7", specificMarket: "Home Total (incl. Extra Innings)", sportsradarType: "Runs", active: true, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_8", specificMarket: "Away Total (incl. Extra Innings)", sportsradarType: "Runs", active: true, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_9", specificMarket: "Odd/Even (incl. Extra Innings)", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_10", specificMarket: "Winning Margin (incl. Extra Innings)", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_11", specificMarket: "1x2", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_12", specificMarket: "Winner & Total (incl. Extra Innings)", sportsradarType: "Specials", active: true, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_13", specificMarket: "Total Hits (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_14", specificMarket: "Total Home Runs (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_15", specificMarket: "Batter Hits (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" },
            { id: "bs_16", specificMarket: "Batter Home Runs (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" },
            { id: "bs_17", specificMarket: "Pitcher Strikeouts (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Pitcher Props" },
            { id: "bs_18", specificMarket: "Batter Total Bases (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" },
            { id: "bs_19", specificMarket: "Batter Runs + Runs Batted In (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" },
            { id: "bs_20", specificMarket: "Innings 1 To 5 - 1x2", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_21", specificMarket: "1st Inning - Winner", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_22", specificMarket: "Innings 1 To 5 - Winner", sportsradarType: "Main", active: false, suggestedCategory: "Game Lines", suggestedSubcategory: "" },
            { id: "bs_23", specificMarket: "Total (over-exact-under) (incl. Extra Innings)", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_24", specificMarket: "Innings 1 To 5 - Home Total", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_25", specificMarket: "Innings 1 To 5 - Away Total", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_26", specificMarket: "1st Inning - Total", sportsradarType: "Runs", active: false, suggestedCategory: "Runs", suggestedSubcategory: "" },
            { id: "bs_27", specificMarket: "Race To X Runs (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_28", specificMarket: "Home To Bat In 9th Inning", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_29", specificMarket: "Team To Win More Innings", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_30", specificMarket: "Team With Highest Scoring Inning", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_31", specificMarket: "Highest Scoring Inning", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_32", specificMarket: "Maximum Consecutive Runs By Either Team", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_33", specificMarket: "When Will The Match Be Decided", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_34", specificMarket: "When Will The 1st Run Be Scored (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_35", specificMarket: "1st Inning - Home To Score", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_36", specificMarket: "1st Inning - Away To Score", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_37", specificMarket: "Home Total Hits (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_38", specificMarket: "Away Total Hits (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_39", specificMarket: "1st Inning - Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_40", specificMarket: "Innings 1 To 5 - Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_41", specificMarket: "1st Inning - Home Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_42", specificMarket: "1st Inning - Away Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_43", specificMarket: "Innings 1 To 5 - Home Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_44", specificMarket: "Innings 1 To 5 - Away Total Hits", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_45", specificMarket: "Home Total Home Runs (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_46", specificMarket: "Away Total Home Runs (incl. Extra Innings)", sportsradarType: "Specials", active: false, suggestedCategory: "Game Props", suggestedSubcategory: "" },
            { id: "bs_47", specificMarket: "X Total Pitcher Strikeouts (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Pitcher Props" },
            { id: "bs_48", specificMarket: "X Total Bases (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" },
            { id: "bs_49", specificMarket: "X Total Batter Runs + Runs Batted In (incl. Extra Innings)", sportsradarType: "Player Props", active: false, suggestedCategory: "Player Props", suggestedSubcategory: "Batter Props" }
        ]
    }
};

// Competitor data for comparison
const competitorData = {
    draftkings: {
        name: "DraftKings",
        football: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Game Lines", subcategories: [] },
                { name: "Passing Props", subcategories: ["Pass Yards", "Pass TDs", "Pass Attempts", "Completions", "Interceptions"] },
                { name: "Rushing Props", subcategories: ["Rush Yards", "Rush TDs", "Rush Attempts"] },
                { name: "Receiving Props", subcategories: ["Receptions", "Receiving Yards", "Receiving TDs"] },
                { name: "TD Props", subcategories: ["Anytime TD", "First TD", "Last TD"] },
                { name: "Game Props", subcategories: [] },
                { name: "Team Props", subcategories: [] },
                { name: "Stat Leaders", subcategories: [] }
            ]
        },
        basketball: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Game Lines", subcategories: [] },
                { name: "Player Points", subcategories: ["Points", "Points 1st Quarter", "Points 1st Half"] },
                { name: "Player Rebounds", subcategories: ["Rebounds", "Offensive Rebounds", "Defensive Rebounds"] },
                { name: "Player Assists", subcategories: ["Assists"] },
                { name: "Player Combos", subcategories: ["Points+Rebounds+Assists", "Points+Assists", "Points+Rebounds"] },
                { name: "3-Point Props", subcategories: ["3-Pointers Made"] },
                { name: "Game Props", subcategories: [] }
            ]
        },
        soccer: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Match Lines", subcategories: [] },
                { name: "Goals", subcategories: ["Total Goals", "Both Teams To Score", "Team Goals"] },
                { name: "Halves", subcategories: ["1st Half", "2nd Half"] },
                { name: "Corners", subcategories: [] },
                { name: "Goalscorers", subcategories: ["Anytime", "First", "Last"] },
                { name: "Specials", subcategories: [] }
            ]
        },
        hockey: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Game Lines", subcategories: [] },
                { name: "Goal Props", subcategories: ["Total Goals", "Team Goals", "Period Goals"] },
                { name: "Player Props", subcategories: ["Goals", "Assists", "Points", "Shots"] },
                { name: "Period Lines", subcategories: ["1st Period", "2nd Period", "3rd Period"] },
                { name: "Game Props", subcategories: [] }
            ]
        },
        tennis: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Match Lines", subcategories: [] },
                { name: "Set Betting", subcategories: ["Correct Score", "Set Handicap"] },
                { name: "Game Props", subcategories: ["Total Games", "Game Handicap"] },
                { name: "Set Props", subcategories: ["1st Set", "2nd Set"] },
                { name: "Player Props", subcategories: ["Aces", "Double Faults"] }
            ]
        },
        baseball: {
            categories: [
                { name: "Popular", subcategories: [] },
                { name: "Game Lines", subcategories: [] },
                { name: "Run Lines", subcategories: ["Total Runs", "Team Runs", "Innings"] },
                { name: "Player Props", subcategories: ["Batter Props", "Pitcher Props"] },
                { name: "Inning Props", subcategories: ["1st Inning", "First 5 Innings"] },
                { name: "Game Props", subcategories: ["Home Runs", "Hits", "Errors"] }
            ]
        }
    }
};

// Make data globally available
window.sportsData = sportsData;
window.competitorData = competitorData;
